### PR TITLE
Active file wasn't visible nor sidebar border

### PR DESCRIPTION
**Pull request by mandm-pt**
I have been using your theme which I like it, but the fact that doesn't highlight the active file is a major issue for me.
As additional I added the border color, which sometimes is useful when extending the size of the left panel

### CODE REVIEW

**Comment by nurmohammed840** [comment]
Thanks for your advice..
I will add this in further update. 

Can you tell me which os you are using? 
In my case **Active file** working fine.But I will add **sidebar border** in further  update.

**Comment by mandm-pt** [comment]
I thought was a bug because I am using Ubuntu 19.10 and active file is all dark

**Comment by nurmohammed840** [comment]
Thanks for your feedback . If anything need to improve feel free to say . I am always listening.

**Comment by mandm-pt** [comment]
> Thanks for your feedback . If anything need to improve feel free to say . I am always listening.

Not sure is a bug on VS but seems like colors defined as RRGGBBAA aren't being displayed. At least on Ubuntu. Yesterday tested your theme on a windows machine and the file you are editing (active/open file) isn't highlighted on the left panel

**Comment by nurmohammed840** [comment]
"workbench.colorCustomizations": {
        "[Just Black]": {
            "list.inactiveSelectionBackground": "#ff0000",  // change colour schema whatever you like.
        }
    },

**Pull request closed without merging**
